# Generated by Django 4.2.13 on 2024-07-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='relation_to_User',
            new_name='author_to_User',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='relation_to_post',
            new_name='comment_to_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='relation_to_user',
            new_name='comment_to_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='relation_to_author',
            new_name='post_to_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='relation_to_category',
            new_name='post_to_category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='relation_to_category',
            new_name='postCategory_to_category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='relation_to_post',
            new_name='postCategory_to_post',
        ),
    ]
